# Generated by Django 3.0.2 on 2020-01-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, null=True, upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, null=True, upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='main.Boss')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, null=True, upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='main.Employee')),
            ],
        ),
    ]
