# Generated by Django 3.0.2 on 2020-01-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200123_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='photo',
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='main.Boss'),
        ),
    ]
