# Generated by Django 3.0.2 on 2020-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200220_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
