# Generated by Django 3.0.2 on 2020-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_boss_skinname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skinname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
