# Generated by Django 3.0.2 on 2020-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
